# ==================
# DiscordX
# ==================

# Please note, if you have NOT changed this,
# the plugin will kick out errors.

# You can obtain this from
# https://discord.com/developers
botToken: "TokenGoesHere"

# The Chat module
chatEnabled: true
chatChannel: 000000000000000000
minecraftToDiscord: "%player%: %message%"
discordToMinecraft: "%player%: %message%"

# The CommandWatcher module
commandWatcherEnabled: true
commandWatcherChannel: 000000000000000000

# The OreMiner module
oreEnabled: true
oreChannel: 000000000000000000

# Bot information
botStatusEnabled: true
botType: "playing"
botStatus: "with DiscordX"
botPrefix: "!"
serverIP: "ChangeThisInTheConfig.yml"